# typed: strict
# frozen_string_literal: true

# Homebrew formula for the cqlite CLI — a local Apache Cassandra SSTable reader.
# Generated by scripts/gen-homebrew-formula.sh in pmcfadin/cqlite; do not edit by
# hand. Each release tag refreshes the version and the per-platform checksums.
class Cqlite < Formula
  desc "Local Apache Cassandra SSTable reader CLI"
  homepage "https://github.com/pmcfadin/cqlite"
  license "Apache-2.0"
  # version is scanned from the release URL path (v0.15.0); see Homebrew audit.

  on_macos do
    on_arm do
      url "https://github.com/pmcfadin/cqlite/releases/download/v0.15.0/cqlite-aarch64-apple-darwin.tar.gz"
      sha256 "5569b7bfffa69e86d2de97138fb416fc8bb1f07d9cbbc8114aba32b0b94dc729"
    end
    on_intel do
      url "https://github.com/pmcfadin/cqlite/releases/download/v0.15.0/cqlite-x86_64-apple-darwin.tar.gz"
      sha256 "549ca252c49a957a967cf3311fa6460c59337c25325fa9f3158fc542d85154ee"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pmcfadin/cqlite/releases/download/v0.15.0/cqlite-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d543cda64ada049b278b04209580b7c61d49dfeb05792655cbd35c084c808efd"
    end
    on_intel do
      url "https://github.com/pmcfadin/cqlite/releases/download/v0.15.0/cqlite-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1a97b39c581e0dea6ab06c25bf5b5b6aa1b74d6c5ab1dd85466725ab85d1b7f2"
    end
  end

  def install
    bin.install "cqlite"
  end

  test do
    assert_match "cqlite", shell_output("#{bin}/cqlite --help")
  end
end
