# typed: strict
# frozen_string_literal: true

# Homebrew formula for the cqlite CLI — a local Apache Cassandra SSTable reader.
# Generated by scripts/gen-homebrew-formula.sh in pmcfadin/cqlite; do not edit by
# hand. Each release tag refreshes the version and the per-platform checksums.
class Cqlite < Formula
  desc "Local Apache Cassandra SSTable reader CLI"
  homepage "https://github.com/pmcfadin/cqlite"
  license "Apache-2.0"
  # version is scanned from the release URL path (v0.13.0); see Homebrew audit.

  on_macos do
    on_arm do
      url "https://github.com/pmcfadin/cqlite/releases/download/v0.13.0/cqlite-aarch64-apple-darwin.tar.gz"
      sha256 "bd77f6373ba8babb745ccf91da915df2df9551f6134bd185892f8efecc2840e0"
    end
    on_intel do
      url "https://github.com/pmcfadin/cqlite/releases/download/v0.13.0/cqlite-x86_64-apple-darwin.tar.gz"
      sha256 "f02e620ae3c77d06b3facc3ec068eef63c259cdf4ef57e06e6469d18796538e0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pmcfadin/cqlite/releases/download/v0.13.0/cqlite-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "82c8a764c0d02f1a01b6f2955c950d3d1dd96dc239a0afc8ae2d2e0f8685c5a1"
    end
    on_intel do
      url "https://github.com/pmcfadin/cqlite/releases/download/v0.13.0/cqlite-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "679eb53582cb5cecc6020d1ad25aed7b754c0513d18912e4b3b77d0c6a938693"
    end
  end

  def install
    bin.install "cqlite"
  end

  test do
    assert_match "cqlite", shell_output("#{bin}/cqlite --help")
  end
end
